import { prisma } from '@/lib/prisma/client';
import { Database } from '@/types/database.types'; // This will be generated by Supabase

export class AuthService {
  /**
   * Creates a new user profile after successful authentication
   */
  static async createUserProfile(userId: string, email: string) {
    // Create a default profile for the new user
    await prisma.profiles.create({
      data: {
        id: userId,
        userId: userId,
        displayName: email.split('@')[0], // Default display name
      },
    });

    // Create an empty draft portfolio for the new user
    await prisma.portfolios.create({
      data: {
        userId: userId,
        slug: `${email.split('@')[0]}-${Math.random().toString(36).substring(2, 10)}`,
        status: 'draft',
        sectionsConfig: {
          hero: true,
          about: true,
          projects: true,
          skills: true,
          experience: true,
          education: true,
          contact: true,
        },
      },
    });
  }

  /**
   * Checks if a user has access to a specific resource
   */
  static async checkUserResourceAccess(
    userId: string,
    resourceId: string,
    resourceType: 'portfolio' | 'project' | 'media'
  ): Promise<boolean> {
    try {
      switch (resourceType) {
        case 'portfolio':
          const portfolio = await prisma.portfolios.findFirst({
            where: {
              id: resourceId,
              userId: userId,
            },
          });
          return !!portfolio;
        
        case 'project':
          const project = await prisma.projects.findFirst({
            where: {
              id: resourceId,
              portfolios: {
                userId: userId,
              },
            },
          });
          return !!project;
        
        case 'media':
          const media = await prisma.media_files.findFirst({
            where: {
              id: resourceId,
              userId: userId,
            },
          });
          return !!media;
        
        default:
          return false;
      }
    } catch (error) {
      console.error('Error checking resource access:', error);
      return false;
    }
  }

  /**
   * Gets the user role
   */
  static async getUserRole(userId: string): Promise<'user' | 'admin'> {
    try {
      const user = await prisma.users.findUnique({
        where: { id: userId },
        select: { role: true },
      });
      
      return (user?.role as 'user' | 'admin') || 'user';
    } catch (error) {
      console.error('Error getting user role:', error);
      return 'user';
    }
  }
}