// This file will be generated by Supabase CLI
// For now, we'll provide a minimal type definition
export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          authProvider: string | null;
          emailVerifiedAt: string | null;
          role: string;
          createdAt: string;
          updatedAt: string;
          deletedAt: string | null;
        };
        Insert: {
          id?: string;
          email: string;
          authProvider?: string | null;
          emailVerifiedAt?: string | null;
          role?: string;
          createdAt?: string;
          updatedAt?: string;
          deletedAt?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          authProvider?: string | null;
          emailVerifiedAt?: string | null;
          role?: string;
          createdAt?: string;
          updatedAt?: string;
          deletedAt?: string | null;
        };
      };
      profiles: {
        Row: {
          id: string;
          userId: string;
          displayName: string | null;
          headline: string | null;
          bio: string | null;
          location: string | null;
          avatarMediaId: string | null;
          websiteUrl: string | null;
          socialLinks: unknown | null;
          resumeMediaId: string | null;
          createdAt: string;
          updatedAt: string;
        };
        Insert: {
          id: string;
          userId: string;
          displayName?: string | null;
          headline?: string | null;
          bio?: string | null;
          location?: string | null;
          avatarMediaId?: string | null;
          websiteUrl?: string | null;
          socialLinks?: unknown | null;
          resumeMediaId?: string | null;
          createdAt?: string;
          updatedAt?: string;
        };
        Update: {
          id?: string;
          userId?: string;
          displayName?: string | null;
          headline?: string | null;
          bio?: string | null;
          location?: string | null;
          avatarMediaId?: string | null;
          websiteUrl?: string | null;
          socialLinks?: unknown | null;
          resumeMediaId?: string | null;
          createdAt?: string;
          updatedAt?: string;
        };
      };
      portfolios: {
        Row: {
          id: string;
          userId: string;
          slug: string;
          status: string;
          sectionsConfig: unknown | null;
          theme: unknown | null;
          publishedAt: string | null;
          createdAt: string;
          updatedAt: string;
          deletedAt: string | null;
        };
        Insert: {
          id?: string;
          userId: string;
          slug: string;
          status: string;
          sectionsConfig?: unknown | null;
          theme?: unknown | null;
          publishedAt?: string | null;
          createdAt?: string;
          updatedAt?: string;
          deletedAt?: string | null;
        };
        Update: {
          id?: string;
          userId?: string;
          slug?: string;
          status?: string;
          sectionsConfig?: unknown | null;
          theme?: unknown | null;
          publishedAt?: string | null;
          createdAt?: string;
          updatedAt?: string;
          deletedAt?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
};