import { createServerClient } from '@/lib/auth/supabase';
import { NextResponse, type NextRequest } from 'next/server';
import { Database } from '@/types/database.types'; // This will be generated by Supabase

export async function updateSession(request: NextRequest) {
  let supabaseResponse = NextResponse.next({
    request,
  });

  const supabase = createServerClient();

  // This will refresh the session if expired - required for Server Components
  // https://supabase.com/docs/guides/auth/auth-helpers/nextjs#managing-server-client-sessions
  const {
    data: { session },
  } = await supabase.auth.getSession();

  // Check if the user is trying to access a protected route without a session
  const isProtectedRoute = request.nextUrl.pathname.startsWith('/(dashboard)');
  const isAdminRoute = request.nextUrl.pathname.startsWith('/(dashboard)/admin');

  if (isProtectedRoute && !session) {
    // Redirect to login for protected routes
    const url = request.nextUrl.clone();
    url.pathname = '/(auth)/login';
    url.searchParams.set('redirect', request.nextUrl.pathname);
    return NextResponse.redirect(url);
  }

  // Additional check for admin routes
  if (isAdminRoute && session?.user?.user_metadata?.role !== 'admin') {
    // Redirect to unauthorized page or dashboard
    const url = request.nextUrl.clone();
    url.pathname = '/(dashboard)';
    return NextResponse.redirect(url);
  }

  return supabaseResponse;
}